language: go

go:
  - 1.7
  - 1.8

before_install:
  - wget "https://github.com/Masterminds/glide/releases/download/v0.13.1/glide-v0.13.1-linux-amd64.tar.gz"
  - tar --strip 1 -xf glide-v0.13.1-linux-amd64.tar.gz
  - export PATH="$(pwd):$PATH"

install:
  - glide install

script:
  - go build .
